// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

import (
	"context"
	"github.com/faizalpribadi/layout/internal/app/handler"
	"github.com/faizalpribadi/layout/internal/app/repository"
	"github.com/faizalpribadi/layout/internal/app/usecase"
	"github.com/faizalpribadi/layout/internal/config"
	"github.com/faizalpribadi/layout/internal/domain"
	"github.com/faizalpribadi/layout/internal/http"
)

// Injectors from container.go:

func NewContainer(ctx context.Context) (domain.Server, error) {
	userRepository := repository.NewUserRepository()
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	feedRepository := repository.NewFeedRepository()
	feedUseCase := usecase.NewFeedUseCase(feedRepository)
	feedHandler := handler.NewFeedHandler(feedUseCase)
	configConfig := config.NewConfiguration()
	server := http.NewServer(userHandler, feedHandler, configConfig)
	return server, nil
}
